[pytest]
pythonpath = google_framework google_framework/alpha_evolve
testpaths = google_framework/alpha_evolve/tests
filterwarnings =
    ignore::DeprecationWarning:urllib3.*
    ignore::DeprecationWarning:OpenSSL.*
