# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'tools/monitoring/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/ae-monitor-ui', '.']

images:
- 'gcr.io/$PROJECT_ID/ae-monitor-ui'
