#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""AlphaEvolve Lineage Forest Graph Visualization Tool.

This script reads an AlphaEvolve `lineage_analysis.json` (and optional
`metrics_analysis.json`) generated by post-processing and renders a visual
evolutionary lineage forest diagram using Graphviz.

Usage Examples:
  # Render the default post-processing lineage graph to PNG:
  python3 tools/monitoring/render_lineage.py

  # Render a specific lineage file to SVG format:
  python3 tools/monitoring/render_lineage.py -l ./ae_postprocess_results/lineage_analysis.json -f svg
"""

import argparse
import json
import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

logger = logging.getLogger("render_lineage")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Render an AlphaEvolve lineage forest diagram to an image file.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "-l",
        "--lineage-file",
        type=str,
        default="./ae_postprocess_results/lineage_analysis.json",
        help="Path to the lineage_analysis.json file produced by ae_monitor.py.",
    )
    parser.add_argument(
        "-m",
        "--metrics-file",
        type=str,
        default=None,
        help="Optional path to metrics_analysis.json to display program scores and states (defaults to same folder as lineage file).",
    )
    parser.add_argument(
        "-o",
        "--output-prefix",
        type=str,
        default=None,
        help="Prefix path for the output image file (defaults to 'lineage_forest' in the same folder).",
    )
    parser.add_argument(
        "-f",
        "--format",
        type=str,
        choices=["png", "svg", "pdf", "dot"],
        default="png",
        help="Output image format.",
    )
    parser.add_argument(
        "--dpi",
        type=str,
        default="300",
        help="Resolution (DPI) for bitmap formats like PNG.",
    )
    return parser.parse_args()


def load_json(file_path: Path) -> dict:
    if not file_path.exists():
        logger.warning(f"File not found: {file_path}")
        return {}
    try:
        with open(file_path, "r", encoding="utf-8") as fp:
            return json.load(fp)
    except Exception as e:
        logger.error(f"Error loading JSON from {file_path}: {e}")
        return {}


def build_dot_graph(lineage_data: dict, metrics_data: dict, dpi: str = "300") -> str:
    """Builds a Graphviz DOT format string representing the lineage tree."""
    # Extract metadata
    parent_to_children = lineage_data.get("parent_to_children", {})
    child_to_parents = lineage_data.get("child_to_parents", {})
    seed_programs = set(lineage_data.get("seed_programs", []))
    depth_map = lineage_data.get("program_depths", {})

    # Collect all node IDs
    all_nodes = set(parent_to_children.keys()).union(set(child_to_parents.keys()))
    for p, children in parent_to_children.items():
        all_nodes.add(p)
        all_nodes.update(children)

    # Build lookup for scores and states from leaderboard or state breakdown
    prog_info = {}
    target_metric = metrics_data.get("target_metric", "score")
    for item in metrics_data.get("leaderboard", []):
        pid = item.get("program_id")
        if pid:
            prog_info[pid] = {
                "state": item.get("state", "COMPLETED"),
                "score": item.get("target_score", item.get("scores", {}).get(target_metric, "N/A")),
                "rank": item.get("rank", ""),
            }

    # Start constructing DOT syntax
    lines = [
        'digraph AlphaEvolveLineage {',
        f'  graph [rankdir=TB, dpi={dpi}, fontname="Helvetica", label="AlphaEvolve Program Lineage Forest", labelloc=t, fontsize=16];',
        '  node [shape=box, style="filled,rounded", fontname="Helvetica", margin="0.2,0.1", fontsize=11];',
        '  edge [fontname="Helvetica", color="#555555", arrowsize=0.8, penwidth=1.2];',
        ''
    ]

    # Group nodes by depth for clean visual hierarchy (subgraphs/ranks)
    depth_groups = {}
    for node in sorted(all_nodes):
        d = depth_map.get(node, 0)
        if d not in depth_groups:
            depth_groups[d] = []
        depth_groups[d].append(node)

    for depth, nodes in sorted(depth_groups.items()):
        lines.append(f'  subgraph cluster_depth_{depth} {{')
        lines.append(f'    label="Generation Depth {depth}";')
        lines.append('    style=dashed; color="#cccccc"; fontcolor="#666666"; fontsize=12;')
        for node in nodes:
            info = prog_info.get(node, {})
            state = info.get("state", "EVALUATING" if node not in seed_programs else "SEED")
            score = info.get("score", "N/A")
            rank = info.get("rank", "")

            # Format score display
            if isinstance(score, float):
                score_str = f"{score:.4f}"
            else:
                score_str = str(score)

            # Node coloring and labels based on state and rank
            if node in seed_programs:
                label_text = f"🌱 SEED (Root)\\nID: {node}\\nState: {state}"
                if score_str != "N/A":
                    label_text += f"\\nScore: {score_str}"
                fillcolor = "#d1e7dd"  # Soft green
                bordercolor = "#0f5132"
                penwidth = "2.0"
            elif rank == 1:
                label_text = f"🏆 BEST (Rank #1)\\nID: {node}\\nScore: {score_str}\\nState: {state}"
                fillcolor = "#fff3cd"  # Soft gold
                bordercolor = "#856404"
                penwidth = "2.5"
            elif state == "COMPLETED" or score_str != "N/A":
                label_text = f"Prog: {node}\\nScore: {score_str}\\nState: {state}"
                if rank:
                    label_text = f"Rank #{rank} | " + label_text
                fillcolor = "#e2e3e5"  # Soft blue/gray
                bordercolor = "#383d41"
                penwidth = "1.2"
            elif state in ["EVALUATING", "GENERATING"]:
                label_text = f"Prog: {node}\\nState: {state}\\n(Pending Eval)"
                fillcolor = "#fff3cd"  # Soft yellow
                bordercolor = "#664d03"
                penwidth = "1.0"
            else:
                label_text = f"Prog: {node}\\nState: {state}"
                fillcolor = "#f8d7da"  # Soft red
                bordercolor = "#842029"
                penwidth = "1.0"

            lines.append(
                f'    "{node}" [label="{label_text}", fillcolor="{fillcolor}", color="{bordercolor}", penwidth={penwidth}];'
            )
        lines.append('  }')
        lines.append('')

    # Add edges (parent -> child)
    lines.append('  # Evolutionary parent to child transitions')
    for parent, children in sorted(parent_to_children.items()):
        for child in sorted(children):
            lines.append(f'  "{parent}" -> "{child}" [label="evolved"];')

    lines.append('}')
    return "\n".join(lines)


def render_graph(dot_content: str, output_prefix: Path, fmt: str) -> str:
    """Renders the DOT content to an image file using graphviz or system dot."""
    dot_file = output_prefix.with_suffix(".dot")
    with open(dot_file, "w", encoding="utf-8") as fp:
        fp.write(dot_content)
    logger.info(f"Saved raw DOT graph specification to: {dot_file}")

    if fmt == "dot":
        return str(dot_file)

    out_file = output_prefix.with_suffix(f".{fmt}")

    # Try Python graphviz library first
    try:
        import graphviz
        src = graphviz.Source(dot_content)
        # graphviz render method automatically appends format extension if not careful,
        # or we can use pipe / render
        src.render(filename=output_prefix.name, directory=str(output_prefix.parent), format=fmt, cleanup=True)
        logger.info(f"Successfully rendered forest graph image via graphviz module: {out_file}")
        return str(out_file)
    except ImportError:
        logger.debug("Python graphviz library not found, falling back to system 'dot' binary.")
    except Exception as e:
        logger.debug(f"Python graphviz render failed ({e}), falling back to system 'dot' binary.")

    # Fallback to system dot executable
    dot_bin = shutil.which("dot")
    if not dot_bin:
        raise RuntimeError(
            "Neither Python 'graphviz' library nor system 'dot' executable was found. "
            "Please install Graphviz (e.g. sudo apt-get install graphviz or pip install graphviz)."
        )

    cmd = [dot_bin, f"-T{fmt}", str(dot_file), "-o", str(out_file)]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
    if res.returncode != 0:
        raise RuntimeError(f"System 'dot' command failed with code {res.returncode}:\n{res.stderr}")

    logger.info(f"Successfully rendered forest graph image via system dot: {out_file}")
    return str(out_file)


def main():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    args = parse_args()

    lineage_path = Path(args.lineage_file).resolve()
    if not lineage_path.exists():
        logger.error(f"Lineage file not found at: {lineage_path}")
        sys.exit(1)

    # Determine metrics file path
    if args.metrics_file:
        metrics_path = Path(args.metrics_file).resolve()
    else:
        metrics_path = lineage_path.parent / "metrics_analysis.json"

    # Determine output prefix
    if args.output_prefix:
        out_prefix = Path(args.output_prefix).resolve()
    else:
        out_prefix = lineage_path.parent / "lineage_forest"

    out_prefix.parent.mkdir(parents=True, exist_ok=True)

    logger.info(f"Loading lineage data from: {lineage_path}")
    lineage_data = load_json(lineage_path)
    if not lineage_data:
        logger.error("Lineage data is empty or invalid.")
        sys.exit(1)

    logger.info(f"Loading metrics data from: {metrics_path}")
    metrics_data = load_json(metrics_path)

    logger.info("Constructing Graphviz DOT forest specification...")
    dot_str = build_dot_graph(lineage_data, metrics_data, dpi=args.dpi)

    try:
        final_file = render_graph(dot_str, out_prefix, args.format)
        print("\n" + "=" * 60)
        print("=== ALPHAEVOLVE LINEAGE FOREST GRAPH CREATED ===")
        print("=" * 60)
        print(f"Input Lineage File : {lineage_path}")
        print(f"Output Graph File  : {final_file}")
        print(f"Format             : {args.format.upper()}")
        print("=" * 60 + "\n")
    except Exception as e:
        logger.error(f"Failed to render graph: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
